apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-170965384
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-170965384
    app.kubernetes.io/part-of: test-app-170965384
  name: python-basic-1709653843ewm
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: python-basic-170965384
    weight: null
status: {}
