apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-170965384
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-170965384
    app.kubernetes.io/part-of: test-app-170965384
  name: python-basic-170965384
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-basic-170965384
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-basic-170965384
    spec:
      containers:
      - image: quay.io/hacdev/ydgytpxp-tenant/test-app-170965384/python-basic-170965384@sha256:e0be139a12a8014c710806f113b75fcde4ccd8e53ba34054db3f5ed289a4e87a
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
